name: eksi-clone-dev

services:
  database:
    container_name: database
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=testdb_eksi
      - POSTGRES_USER=testuser_eksi
      - POSTGRES_PASSWORD=dummypass
    ports:
      - "5432:5432"
    networks: 
      - main-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser_eksi -d testdb_eksi"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

    networks: 
      - main-network
      
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    env_file: ./frontend/.env
    ports:
      - "5173:5173"
    networks: 
      - main-network

networks:
  main-network:
