spring:
  application:
    name: eksi

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

  datasource:
    url: jdbc:postgresql://localhost:5432/testdb_eksi
    username: testuser_eksi
    password: dummypass

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    # show-sql: true

  # sql:
  #   init:
  #     mode: always

  # security:
  #   user:
  #     name: koray
  #     password: 1234

  data:
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: deba9893aca64f00b097a8b074ffa346deba9893aca64f00b097a8b074ffa346
  access:
    expirationMin: 140
  refresh:
    expirationMin: 1440

app:
  upload:
    root: uploads
    public-url-prefix: /uploads
    profile-image:
      max-size-bytes: 2097152
