spring:
  datasource:
    url: jdbc:postgresql://database:5432/testdb_eksi
    username: testuser_eksi
    password: dummypass

  data:
    redis:
      host: redis
      port: 6379

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

app:
  upload:
    root: /app/uploads
    public-url-prefix: /uploads
    profile-image:
      max-size-bytes: 2097152
